definitions:
  github_com_teezzan_candles_internal_controller_ohlc_data.GeneratePresignedURLResponse:
    properties:
      filename:
        type: string
      url:
        type: string
    type: object
  github_com_teezzan_candles_internal_controller_ohlc_data.GetOHLCResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_teezzan_candles_internal_controller_ohlc_data.OHLC'
        type: array
      page:
        type: integer
    type: object
  github_com_teezzan_candles_internal_controller_ohlc_data.OHLC:
    properties:
      close:
        type: number
      high:
        type: number
      low:
        type: number
      open:
        type: number
      symbol:
        type: string
      unix:
        type: integer
    type: object
  github_com_teezzan_candles_internal_controller_ohlc_data.ProcessingStatusEntity:
    properties:
      created_at:
        type: string
      error:
        $ref: '#/definitions/github_com_teezzan_candles_internal_null.String'
      file_name:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  github_com_teezzan_candles_internal_httputil.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  github_com_teezzan_candles_internal_null.String:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
info:
  contact: {}
  description: This is API specification for Candels, a OHLC data API platform.
  title: Candles API
  version: "1.0"
paths:
  /data:
    get:
      description: The endpoint returns the OHLC points for a particular Symbol for  the
        given time range
      parameters:
      - description: This is the symbol of the OHLC token
        example: BTC
        in: query
        name: symbol
        required: true
        type: string
      - description: UNIX time representation of the start time
        example: "10344553332"
        in: query
        name: from
        required: true
        type: string
      - description: UNIX time representation of the end time
        example: "101019283847"
        in: query
        name: to
        type: string
      - description: page of response
        example: 1
        in: query
        name: page
        type: integer
      - description: Number of OHLC datapoints per page
        example: 5
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_controller_ohlc_data.GetOHLCResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
      summary: returns the OHLC points for the given time range
    post:
      consumes:
      - multipart/form-data
      description: The endpoint takes a small CSV file upload and processes it. Max
        file size is 30MB.
      parameters:
      - description: CSV file to be processed
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
      summary: Takes a CSV file upload and processes it
  /generate_url:
    get:
      description: The endpoint generates a pre-signed URL for the given file name
        for uploading on S3, It supports huge files
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_controller_ohlc_data.GeneratePresignedURLResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
      summary: Generates a pre-signed URL for the given file name for uploading on
        S3
  /status/{filename}:
    get:
      description: The endpoint returns the status of the file processing
      parameters:
      - description: This is the filename
        example: '"7d2f5f5c-0b1a-4b1e-9c5e-1c2d3e4f5g6h.csv"'
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_controller_ohlc_data.ProcessingStatusEntity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_teezzan_candles_internal_httputil.ErrorResponse'
      summary: returns the status of the file processing
swagger: "2.0"
