name: Pull-Request

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  testOnly:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To be able to compare with 'main' branch
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Install build dependencies
        run: go mod download
      - name: Run unit tests
        run: make test
